"""add consent_logs table

Revision ID: 48b9bb519603
Revises: 6f7e3227af53
Create Date: 2026-03-10 09:48:13.394620+09:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b9bb519603'
down_revision: Union[str, None] = '6f7e3227af53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False, comment='PRIVACY_POLICY | TERMS_OF_SERVICE | MARKETING | PARTNER_SHARE'),
    sa.Column('version', sa.String(length=20), nullable=False, comment="Policy version at time of consent (e.g. '2026-01-01')"),
    sa.Column('granted', sa.Boolean(), nullable=False, comment='True=granted, False=withdrawn'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True, comment='Additional context (e.g. withdrawal reason)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_logs_user_id'))

    op.drop_table('consent_logs')
    # ### end Alembic commands ###
