"""add_realtrade_cache_tables

Revision ID: a77d19fd80b8
Revises: a1b2c3d4e5f6
Create Date: 2026-03-16 21:33:19.962571+09:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77d19fd80b8'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_handoffs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_handoffs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('handoff_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('calculation_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contact_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('consent_privacy', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('consent_partner', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('memo', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), server_default=sa.text("'REQUESTED'"), nullable=False),
    sa.Column('requested_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['track1_calculations.calculation_id'], name=op.f('fk_handoffs_calculation_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
