/**
 * @deprecated 이 파일은 호환성을 위해 유지됩니다.
 * 새 코드에서는 "./constants/index" 경로를 사용하세요.
 * 도메인별 분리: youthTaxConstants, propertyTaxConstants, lifecycleConstants 등
 */
export {
	YOUTH_TAX_REDUCTION_CONFIG,
	INELIGIBLE_REASON_LABELS,
	MILITARY_SERVICE_TYPE_LABELS,
	EXCLUDED_INDUSTRY_CODES,
	EXCLUDED_INDUSTRY_LABELS,
	SIX_WAY_SCENARIO_LABELS,
	DONEE_RELATION_OPTIONS,
	SURCHARGE_DEADLINE,
	TAX_SERVICE_CARDS,
	HOME_BANNERS,
	LIFECYCLE_SERVICES,
	LIFECYCLE_STAGES,
	DISCLAIMER_TEXTS,
	REPORT_DISCLAIMERS,
	MOCK_SAVED_SIMULATIONS,
	CONSULTANT_SPECIALTY_LABELS,
	MOCK_CONSULTANTS,
} from "./constants/index";
